.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py pbc_simple

clean:
	rm -f pbc_simple.md Doxyfile
	rm -rf html

cleaner:
	rm -f pbc_simple.ipynb pbc_simple.py pbc_simple.md Doxyfile
	rm -rf html

